### ISSUE TITLE
getherbert.com css issue

### ISSUE THREAD

**Issue by codesman** [getherbert/herbert#1]
I am experiencing a problem with the `<pre>` elements on the entire site at http://getherbert.com

None of the code in `<pre>` is visible.  Looks like a JavaScript issue because you can see the text flash briefly on pageload but then all of the elements turn totally gray.

Problem reproduced on Chrome 40.0.2214.94 and Safari 8.0.2 on OSX 10.10 and 10.8.5

![screen shot 2015-01-30 at 9 43 52 am](https://cloud.githubusercontent.com/assets/1653589/5980397/da0c2286-a864-11e4-9702-b4d9cc032ded.png)

**Comment by jasonagnew** [comment]
Thanks for reporting. In the meantime you can view the docs in markdown here: https://github.com/getherbert/docs
