### ISSUE TITLE
HERBERT_ENV

### ISSUE THREAD

**Issue by abdelkrimdev** [getherbert/herbert#101]
hello where can i define the HERBERT_ENV variable ?

**Comment by dcalvert** [comment]
There are a few ways. A simple one would be to set a variable in your .htaccess file, such as:

`SetEnv app_env production`

and then grab that in your plug-in by adding:

`define('HERBERT_ENV', getenv('app_env'));`

in the plugin.php file.

**Comment by abdelkrimdev** [comment]
thanks a lot :)

**Comment by jeremyzahner** [comment]
@onnimonni This one should be labeled question and be closed.
