### ISSUE TITLE
Paginator class not found

### ISSUE THREAD

**Issue by giwrgos88** [getherbert/herbert#104]
From your documentation you are using Laravel components like the Illuminate. On laravel there is a function called pagination where you can use it on your model to paginate your queries. Inside the "vendor/illuminate/database/Eloquent/Builder.php" of your framework the pagination option is available as well you including it on the top of the Builder class

```
<?php

namespace Illuminate\Database\Eloquent;

use Closure;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\Pagination\Paginator;
use Illuminate\Database\Query\Expression;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Database\Query\Builder as QueryBuilder;

class Builder
{}
```

but you haven't added it into the Illuminate folder, 
<img width="867" alt="screen shot 2016-04-04 at 10 42 08" src="https://cloud.githubusercontent.com/assets/3164113/14241035/ef6ba666-fa51-11e5-8c64-fd74108fb91f.png">

When I run the pagination on my model I'm getting the following error message

> Fatal error: Class 'Illuminate\Pagination\Paginator' not found in /Applications/XAMPP/xamppfiles/htdocs/testing/wp-content/plugins/testing/vendor/illuminate/database/Eloquent/Builder.php on line 463

Can you add it on your next release?

Thank you

**Comment by ConnorVG** [comment]
You could include it yourself if you wish to use it, I imagine it's not included by default because it's quite a few extra classes that most people won't use.

`composer require illuminate/pagination "~5.0"` will pull this in for you.

**Comment by giwrgos88** [comment]
@ConnorVG ok thanks a lot
