### ISSUE TITLE
How I can extend Twig so I can execute wordpress functions?

### ISSUE THREAD

**Issue by giwrgos88** [getherbert/herbert#105]
I want to execute some wordpress functions like do_shortcode inside the twig. I found this [http://twig.sensiolabs.org/doc/advanced.html](http://twig.sensiolabs.org/doc/advanced.html) but I don't know where to put this files in the herbert in order to extend the twig and allow php functions to be executed in the template

**Comment by ConnorVG** [comment]
Hey. If you wish to add existing functions, you'll just need to extend the service container's value for `twig.functions`.

You can do this simply by calling:

``` php
herbert()->extend('twig.functions', function ($functions) {
    return array_merge($functions, [
        'do_shortcode',
        // ... any other functions here etc.
    ]);
});
```

I advise you place this as early in your code as possible as it will have to be executed before Twig is resolved :smile:

**Comment by giwrgos88** [comment]
I did it like this

```
$function = new Twig_SimpleFunction("do_shortcode", function ($arg1) {
    echo $arg1;
});
herbert('twig')->addFunction($function);
```

**Comment by ConnorVG** [comment]
It may be wise going my method if you plan on adding any more, we added `twig.functions` in an attempt to avoid having people have to repeat a lot of that boilerplate code.

Whatever you're comfortable with though, in the long run. Glad you got it sorted mate :smile:

**Comment by giwrgos88** [comment]
@ConnorVG I will go with your way but still is not printing the do_shortcode

**Comment by ConnorVG** [comment]
Are you sure it is 100% executing pre-render?

**Comment by giwrgos88** [comment]
@ConnorVG maybe the do_shortcode is loaded after my provider and that's way is not working
