### ISSUE TITLE
Can i use herbert in wordpress template design

### ISSUE THREAD

**Issue by hamedmoody** [getherbert/herbert#108]
Hi
herbert is great for plugin, but i want use herber in wordpress template. is posible? if ok, How?
Thanks

**Comment by onnimonni** [comment]
As far as I know this is out of scope for herbert. Your question is a bit vague and you could be more specific. How are you planning to use herbert in theme templating? If you want to use use for example twig templating in your themes you can use timber: http://upstatement.com/timber/.

**Comment by hamedmoody** [comment]
Thanks onnimonni
