### ISSUE TITLE
How to create a Page post in Herbert? Or how to get the footer/header and sidebars in Herbert views?

### ISSUE THREAD

**Issue by dryajov** [getherbert/herbert#110]
Whats the best way of creating a real Page in Herbert? It seems like routes allow you to render anything, but they are not a post of any sort in WP. For my use case, that might not be a problem, but I do need the header and footer to be present, is there any way of accomplishing that with Herbert without having to rely on Pages?

**Comment by moazam1** [comment]
I am struggling with same issue. Any help will be greatly appreciated.

**Comment by dryajov** [comment]
I actually resorted to using short codes for dynamic content generation. Take a look at wp / Herbert docs for short codes.
