### ISSUE TITLE
problems with PluginAccessorTrait and magic method overuse

### ISSUE THREAD

**Issue by unstoppablecarl** [getherbert/herbert#12]
I don't see the need for the `PluginAccessorTrait`. I think it causes more confusion when accessing other things. Is there a reason for it other than being able to do `$this->whatever` instead of `$this->plugin->whatever` ? I don't think it is worth the cost of performance, clarity, and making ide lookups impossible. There are a lot of these magic methods being used for little or no reason I can see.

**Comment by unstoppablecarl** [comment]
I wrote this improved version of the Plugin class.

https://gist.github.com/unstoppablecarl/9c478e968b0ad60649f6

**Improvements**
- lazy load object instances instead of loading all even when not used
- configurable classes
- configurable build files
- isolated function context for each required file
- removed magic methods
- defined all class properties (adminUrl, siteUrl, name, config)
- config array is injected to constructor instead of depending on relative path from class file
- removed `define('HERBERT_CONFIG', true);` I don't know why you would need to protect execution of a file that simply returns an array.

I put it in a gist to see if anyone was interested in massive improvements. If @jasonagnew is I will make a pull request with all the necessary changes.

**Comment by bruno-barros** [comment]
I think you have a typo here:

```
if(!empty($config['lazy_load_classmap'])){
            $this->lazyLoadClassMap = array_merge($this->lazyLoadClassMap, $config['lazy_load_class_map']);
        }
```

**Comment by unstoppablecarl** [comment]
@bruno-barros yep. fixed

**Comment by jasonagnew** [comment]
@unstoppablecarl Thanks for taking the time to look at this in such detail.

I’m not a massive fan of using magic methods. I agree that there is some IDE issues when using them, we used `@property` to help with that.

The main reason for using `PluginAccessorTrait` was that the `BaseController` didn’t necessary need to be updated by the user if they updated the framework folder. 

I personally preferred having `$this->class->method` rather than `$this->plugin->class->method` but if people feel its the wrong approach then I’m happy to change it. Especially if its confusing or making the framework harder to understand.

**Comment by ConnorVG** [comment]
Your implementation of this, @unstoppablecarl, isn't desirable. It seems the way you have gone about it is very convoluted for what it is. This issue has already been resolved though I'm open to thoughts on the current implementation.

Basically the current implementation is the use of a main 'Application' instance that acts as an IoC container so overrides and bindings etc work really nicely (thanks to Illuminate\Support). This allows us to do stuff such as `$app['router']` etc

**Comment by unstoppablecarl** [comment]
I have updated to gist to keep the api the same, using __get to lazy load properties. The magic method is only used the first time a property is called. What are your thoughts on that?

Is there any feedback on the non magic method changes made? no one has given any.

@ConnorVG When you say `$app` (Application instance) do you mean `$plugin` (`Herbert\Framework\Plugin`)? I see how the `$plugin` is used as an IoC container/service locator. I  don't see `Illuminate\Support` used anywhere in the code could you please explain? I don't know what you mean by `$app['router']`.

**Comment by ConnorVG** [comment]
Hey @unstoppablecarl :-) - sorry for the poor explanation on my part there.

I'm currently working on a rewrite of Herbert as to comfortably allow for multiple plugins. The current progress is showing good results.

The new developments on Herbert have ended up in it have one global `Application` instance which extends `Illuminate/Supports`'s `Container` class. This class is then used (along side optional service providers) to load in the required instances to make Herbert work. This includes `Shortcode`, `Router` etc. The way you will be able to access these in the future will be either method / constructor injection (when a class or method is resolved or called via the IoC container `Application` which is _always_ used from internal Herbert functionalities such as `Controller` routing).

The new system will allow for more than one `Plugin` instance which is resolved via the IoC container so anything within your `Plugin` will always be able to access anything Herbert has to offer :grin:!

This rewrite will soon be available on a separate branch for people to check out so we can see if it is the way forward for this framework.

Cheers!

**Comment by unstoppablecarl** [comment]
Using the `Illuminate\Support` Container class would be even better than what I suggested. I look forward to seeing it.

**Comment by bruno-barros** [comment]
I have a project using Laravel components inside WordPress.
https://github.com/bruno-barros/w.eloquent
Would be nice to use Herbert sharing the same container of my application.

**Comment by jasonagnew** [comment]
@unstoppablecarl @bruno-barros  Hey everyone the rewrite branch is [here](https://github.com/getherbert/herbert/tree/rewrite). The README gives an overview, with feedback to be posted [here](https://github.com/getherbert/herbert/issues/14). Thanks :)

**Comment by jasonagnew** [comment]
The rewrite is now live and working with example plugin coming this weekend.
