### ISSUE TITLE
Shortcode Argument Names as String

### ISSUE THREAD

**Issue by 69dev69dev** [getherbert/herbert#122]
Hi,,, i am newbie in wp plugin development...
i try for creating shortcode using Argument Names , eg:
`[showMe keyword=foo bar]`
but in view, i just get **foo**, not **foo bar**.
how i can showing foo bar as string not array ?

This my code : 

```
// shortcodes.php

$shortcode->add(
    'showMe',
    'myAppApi::showMeVal',
    [
        'keyword' => 'keyword'
    ]
);
```

and my api like this:

```
// api.php

$api->add('showMeVal', function($keyword) {
    return (new ShortcodeController)->showmeact($keyword);
});
```

Thanks so much for the great framework :)

**Comment by arippberger** [comment]
@David-Kurniawan when using your shortcode, are you using quotes like `[showMe keyword="foo bar"]`?

**Comment by 69dev69dev** [comment]
@arippberger
Thanks so much,,,

Sorry....
i forgot about that....

now work perfect....

**Comment by arippberger** [comment]
No problem! Good luck!
