### ISSUE TITLE
Help with routes

### ISSUE THREAD

**Issue by giwrgos88** [getherbert/herbert#124]
Hello, I'm having a small issue with some of my routes. I'm not receiving any error or warning and some routes are working and some others are throwing page not found. 

For example I did this simple route for testing purposes 

```
$router->get([
    'as'   => 'simpleRoute',
    'uri'  => '/simple',
    'uses' => function()
    {
        return 'Hello World';
    }
]);
```

and throws "page not found". I checked the permalinks(also tried to update them again), but still the same issue. 

I have installed plugins  
WP Super Cache

Server has installed
memcache
opcache

Does anyone had this problems?

**Comment by beatelite** [comment]
I have this problem too but when trying to use a controller to render a twig file as the view. The simple/ route worked for me. It doesn't help that NONE of the example plugins use the $router resource at all so examples are limited to the documentation which is dearth of real world examples.

**Comment by giwrgos88** [comment]
The issue was a plugin that I have installed for memcached. Create a new issue, paste your code and tag my to help you if you want.
