### ISSUE TITLE
Enqueue issues

### ISSUE THREAD

**Issue by Tekhed44** [getherbert/herbert#126]
Hi, 

I'm having issues with css bleeding into my admin panel. Not sure what the exact cause is but I also noticed my enqueue panel filter only works with the slug not the panel name as the instructions show. Maybe I'm misunderstanding something. 

Has anyone else encountered this? Thank you.

**Comment by Tekhed44** [comment]
Solution: Turns out the solution had nothing to do with getherbert or enqueue, but rather the "font-family" attribute in every one of my style sheets was conflicting with WordPress. Nothing else conflicts. I have no idea why this happened, but I managed to fix the issue by removing that attribute.

**Comment by jeremyzahner** [comment]
@Tekhed44 Thanks for letting us know. I'd close the issue. Feel free to reopen it if the incident finally has something to do with herbert.
