### ISSUE TITLE
route in admin

### ISSUE THREAD

**Issue by imajim** [getherbert/herbert#135]
Hello,

How to create route in admin ?  I wrote this : 
**_Inner route.php (loaded)_** 

```
$router->get([
        'as'   => 'printFiche',
        'uri'  => '/wp-admin/admin/print-fiche-{postId}',
        'uses' => __NAMESPACE__ . '\Controllers\AnnonceController@printFiche'
    ]);
```

And the controller : 

```
public function printFiche($postId)
    {
        var_dump($postId);
        die('toto');
    }
```

But i've got a blank screen.

Thx for help.

**Comment by giwrgos88** [comment]
@imajim did you tried the route to work first without any parameter? second, the blank screen indicates that there is an issue. do you have debug enable?

**Comment by sajadghawami** [comment]
@imajim i tried your code, and it seems to work, i tried it with this route:

``` php
/wp-admin/admin/print-fiche-12
```

**Comment by jeremyzahner** [comment]
@imajim Is this issue still present for you?

**Comment by imajim** [comment]
Hi,

Sorry for my later response  ^^

i juste change : 
`'/wp-admin/admin/print-fiche-{postId}',`
by 
`'/admin/print-fiche-{postId}',`

and it's ok ! ^^
