### ISSUE TITLE
[Discuss] New Framework Rewrite

### ISSUE THREAD

**Issue by jasonagnew** [getherbert/herbert#14]
Feedback for the Herbert rewrite should go here:

https://github.com/getherbert/herbert/tree/rewrite

**Comment by mikehhhhhhh** [comment]
How much will change as part of the rewrite? 

Will I be able to drop my plugin into the rewritten framework without too much work?

**Comment by ConnorVG** [comment]
We're hoping not too much work would be needed to convert over from the current to the rewrite but it will require some work. Sorry!

**Comment by jasonagnew** [comment]
We aim to keep the amount of work to a minimum, I'd say around an hour on a full plugin. The main change will be add a Namespace to your Controllers and Models.

**Comment by dmgawel** [comment]
What is the timeline for the rewrite? I'm just about to start a plugin with Herbert and wondering if should I wait.

**Comment by ConnorVG** [comment]
Hey @dmgawel, the rewrite has all the features of the dev branch if that's what you're asking :-)

**Comment by ghost** [comment]
can you give me some hints how to handle route params... this here:

```
$router->get([
    'uri' => '/foo/:id',
    'uses' => function (Icorm\Controller\OpportunityController $controller)
    {
        die('##');
    }
]);
```

doesn't get called with url /foo/1

**Comment by ghost** [comment]
damn first read code then post questions ;-)
for users with same problem the uri needs to read
    'uri' => '/foo/{id}',

**Comment by mikehhhhhhh** [comment]
Hi Guys, I'm starting a new project having already used the existing Framework once. Should I be using the rewrite to start the new one?

**Comment by ConnorVG** [comment]
The rewrite is recommended though the docs are not yet done.

**Comment by mikehhhhhhh** [comment]
Is there an example plugin to show the new use or namespacing? 

Or is it just a case of 
    namespace MyName\PluginName; 

or something?

**Comment by mikehhhhhhh** [comment]
I meant to add is it a case of just adding a namespace to my controllers and models?

Apparently the edit functionality isn't working.

**Comment by mikehhhhhhh** [comment]
Is anyone able to help me with the basics of the Rewrite?

I've created a Controller in plugin/controllers with the Namespace of MyVendor\MyPluginName and it extends BaseController.

In Routes, I've tried using MyVendor\MyPluginName\MyController@method, I've tried MyController@method but in both instances, I get an error saying 'Class MyVendor\MyPluginName\MyController not found'

What am I missing?

**Comment by ghost** [comment]
have you done: composer dump-autoload

**Comment by mikehhhhhhh** [comment]
I think that was it, although it turns out that I'd cloned the wrong branch and wasn't using the rewrite at all.

I've since corrected that, and I've already had two errors inside Application.php.

One requiring a method basePath() to exist and  typecasting $parameters in the make() method to satisfy the Interface.

I'm curious how these issues have come about?

**Comment by ghost** [comment]
this happens because herbert implements a newer laravel class where those methods are required.
im also not that sure what the plan here is... and how the future goes... everything gets a little silent around herbert

**Comment by mikehhhhhhh** [comment]
I've created a pull request for my fixes here: https://github.com/getherbert/framework/pull/4

What have others done? Would I be perhaps be better specifying an older version of Illuminate?

**Comment by jasonagnew** [comment]
The rewrite is now live and working with example plugin coming this weekend.
