### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by EresDev** [getherbert/herbert#144]
In your documentation on http://getherbert.com/0.9/panels where it says:

``` php
$panel->add([
    'type'   => 'panel',
    'as'     => 'mainPanel',
    'title'  => 'My Plugin',
    'slug'   => 'myplugin-index',
    'icon'   => Hepler::assetUrl('/img/icon.png'),
    'uses'   => __NAMESPACE__ . '\Controllers\AdminController@index'
]);
```

`Hepler` is wrong. It should be `Helper`

**Comment by jeremyzahner** [comment]
@EresDev Would you submit a PR to https://github.com/getherbert/docs to fix this? 
Your help would be much appreciated!

**Comment by kalinichenko88** [comment]
@jeremyzahner https://github.com/getherbert/docs/pull/9
