### ISSUE TITLE
Relative symlinks break deployment

### ISSUE THREAD

**Issue by jan-koch** [getherbert/herbert#153]
Hey,
first of all, thanks for putting all this work into Herbert. I love it!

Just tried it with DeployHQ, but it seems that relative symlinks are breaking the deployment. The SFTP user I use for deployment is chrooted, which should be the case for most web hosting environments.

Using absolute symlinks is no option, as every hosting environment is different. Using non-chrooted SFTP users won't work for most web hosts either.

Just wondering how to solve this or whether I'm missing something :-)

Looking forward to hearing your thoughts on this question.

Best,
Jan

**Comment by jeremyzahner** [comment]
@jan-koch Hey Jan!

Thanks for using herbert.
Could you elaborate a little further how exactly you are deploying?
And could you provide logs etc.

**Comment by jan-koch** [comment]
Hey @jeremyzahner , sorry for ignoring this issue for such a long time.
I have moved from herbert to wppb.me for plugin dev, so I'll close this issue here. Cannot say if it still persists :-/ 

Thanks for your work!

Best,
Jan
