### ISSUE TITLE
Issue on getting access of Route, when i insalled wordpress in sub-directory 

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [getherbert/herbert#158]
I can't access any routes, when i installed my core wordpress in sub-directory.

**Comment by sajadghawami** [comment]
Have you turned you permalinks to "post link"?

Settings ->Permalinks -> Post name

**Comment by shankarThiyagaraajan** [comment]
Except my plugin route, all wordpress posts are working fine.
If i place wordpress directory in main folder, i having no issue on calling route function.
But in sub-directory only the issue.

**Comment by sajadghawami** [comment]
Please be more clear, and post your route definition.

**Comment by shankarThiyagaraajan** [comment]
Thank you, My prob solved on re-installation.
Thanks for your Response ...
