### ISSUE TITLE
Allow CORS Requests

### ISSUE THREAD

**Issue by ken-bem** [getherbert/herbert#161]
I can't submit a pull request to add CORS to the framework, I get a 403 error, anyone who may be able to help?

**Comment by jeremyzahner** [comment]
@ken-bem I can see you've submitted the PR.

**Comment by ken-bem** [comment]
@jeremyzahner is the any way i can become a contributor with herbert?

**Comment by jeremyzahner** [comment]
@ken-bem You'll be a contributor as soon as one of your pull requests gets merged. =)

**Comment by ken-bem** [comment]
@jeremyzahner if i make a pull request, will someone at least look at it? because i made one 3 months ago on the framework itself and nobody accepted/rejected it

**Comment by jeremyzahner** [comment]
@ken-bem Promised. ;-) I also added a reaction to your last one just now.

**Comment by ken-bem** [comment]
@jeremyzahner I updated my pull request, if you could check it out i would appreciate it
