### ISSUE TITLE
No view with controller

### ISSUE THREAD

**Issue by ElodieBerthaud** [getherbert/herbert#163]
Hello,

I'd like to return a view from my controller:

controller.php:
```
namespace FormulaireClient\Controllers;


class FormulaireController
{
	function __construct()
	{
		
	}
	
    public function showView()
	{
		return view('@FormulaireClient/formulaire.twig', [
		'title'		=>	'formulaire',
		'content'	=>	'répondez à ce court questionnaire'
		]);
	}
}
```
routes.php:

```
namespace FormulaireClient;

$router->get([
    'as'   	=> 'simpleRoute',
    'uri'  	=> '/formulaire',
'uses'	=>	__NAMESPACE__ . '\Controllers\FormulaireController@showView'
]);
```

formulaire.twig:

`<div>TEST</div>`

The router works fine but when I use a controller to get the view, I've got nothing wrote on the screen.
But if I just have a simple route without using a controller (just like for exemple: return 'Hello World'), that works fine.

Sorry for bad English, I'm French.

I hope that you could have some answers for me...

thank you in advance :)

ps: I'm beginner in programing, so sorry for mistakes I could make.

**Comment by ken-bem** [comment]
Do you get a blank screen or the word test?

**Comment by ElodieBerthaud** [comment]
Thks for your answer!

I've got a blank screen. Nothing in my formulaire.twig is posted.

**Comment by ElodieBerthaud** [comment]
I've found the issue! The mistake is from me ... I had my 'vews' folder was named 'view'.

It was all my fault.

Sorry for this!

**Comment by ken-bem** [comment]
That what i was going to suggest, to check folder path, good that you resolved ! :)

**Comment by ElodieBerthaud** [comment]
Thank you !

**Comment by jeremyzahner** [comment]
@ElodieBerthaud Thanks for using Herbert.
I'm closing this issue since it seems to be resolved for you.
Feel free to reopen it if thats not the case.
