### ISSUE TITLE
Enqueue js/css files when view is loaded via shortcode

### ISSUE THREAD

**Issue by aidanayala** [getherbert/herbert#167]
I display my frontend UI when a shortcode is placed within a page.

How can I use enqueue to load the necessary js/css when this view / shortcode is used?

**Comment by giwrgos88** [comment]
You can do the following and use the filter to load the js or css for the specific page that you use your shortcode

```php
$enqueue->front([
    'as'  => 'postsJS',
    'src' => Helper::assetUrl('/js/post.js')
'filter' => [ 'panel' => ['mainPanel', 'subPanel'] ]
]);
```

for more [reference](http://getherbert.com/0.9/enqueue)

**Comment by aidanayala** [comment]
Thank you
