### ISSUE TITLE
dependency error.

### ISSUE THREAD

**Issue by Arunkumarcs** [getherbert/herbert#169]
Hi

I'm getting below dependency error when installing through composer.

> Plugin could not be activated because it triggered a fatal error.

> Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider

**Comment by ken-bem** [comment]
I am also getting this error, it is recent and it broke one of my plugins

**Comment by Arunkumarcs** [comment]
I think it's because of some update in Illuminate package caused brake in Herbert.

**Comment by sergiorodenas** [comment]
@Arunkumarcs @ken-bem I've solved it by setting this on the **composer.json** :
`"minimum-stability": "stable",`

**Comment by jeremyzahner** [comment]
@Rodenastyle Having a minimum stability of stable is generally a good idea.
Feel free to reopen this issue if it isn't properly resolved for you.

**Comment by Arunkumarcs** [comment]
Hi,

I got below error when i tried to use controller in my routes can u suggest me what went wrong and thanks for the previous update @Rodenastyle 

> Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in D:\PHP\htdocs\T\cluster\wp-content\plugins\akClusterAdmin\vendor\illuminate\container\Container.php:763 Stack trace: #0 D:\PHP\htdocs\T\cluster\wp-content\plugins\akClusterAdmin\vendor\illuminate\container\Container.php(644): Illuminate\Container\Container->build('Illuminate\\Cont...', Array) #1 D:\PHP\htdocs\T\cluster\wp-content\plugins\akClusterAdmin\vendor\getherbert\framework\Herbert\Framework\Application.php(974): Illuminate\Container\Container->make('Illuminate\\Cont...', Array) #2 D:\PHP\htdocs\T\cluster\wp-content\plugins\akClusterAdmin\vendor\illuminate\database\Connectors\ConnectionFactory.php(130): Herbert\Framework\Application->make('Illuminate\\Cont...') #3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}() #4 D:\PHP\htdocs\T\cluster\wp-content\plugins\akClusterAdmin\vendor\illuminate\databas in D:\PHP\htdocs\T\cluster\wp-content\plugins\akClusterAdmin\vendor\illuminate\container\Container.php on line 763


Thanks,

**Comment by jeremyzahner** [comment]
Hi @Arunkumarcs Please open a new issue for this particular case. (And also check if this problem hasn't been covered in any previous issues).

**Comment by mintaraga** [comment]
Hi, changing setting this on the **composer.json** :
`"minimum-stability": "stable"`
it does not work for me. the error below still happen:

> Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider' in ...

anyone have other alternative way to solved this issues?

**Comment by mintaraga** [comment]
Hi All, was found alternative way to fix it for some others that still got experience with the error.

for me this fixed https://github.com/getherbert/herbert/issues/172#issuecomment-275444775
solved the problem
