### ISSUE TITLE
I can't start plugin in WP dashboard..

### ISSUE THREAD

**Issue by rafarcheo** [getherbert/herbert#170]
Hi, 
I can't start plugin in WP dashboard..
When I start plugin I getting code of error: 

` Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider' in C:\xampp\htdocs\my-wordpress\wp-content\plugins\herbert-test\vendor\illuminate\container\Container.php:819 Stack trace: #0 C:\xampp\htdocs\my-wordpress\wp-content\plugins\herbert-test\vendor\illuminate\container\Container.php(757): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter)) #1 C:\xampp\htdocs\my-wordpress\wp-content\plugins\herbert-test\vendor\illuminate\container\Container.php(732): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter)) #2 C:\xampp\htdocs\my-wordpress\wp-content\plugins\herbert-test\vendor\illuminate\container\Container.php(710): Illuminate\Container\Container->resolveDependencies(Array) #3 C:\xampp\htdocs\my-wordpress\wp-content\plugins\herbert-test\vendor\illuminate\container\Container.php(565): Illuminate\Container\Container->buil in C:\xampp\htdocs\my-wordpress\wp-content\plugins\herbert-test\vendor\illuminate\container\Container.php on line 819`

_(I use xampp (php 5.6.28) on win 10 and herbert 0.9)_

**Comment by ken-bem** [comment]
On the composer.json file, add "stable" to the minimum-stability key

**Comment by rafarcheo** [comment]
it work!
