### ISSUE TITLE
I18n problem in panels.php

### ISSUE THREAD

**Issue by angelocala94** [getherbert/herbert#179]
Hi, I have a problem with i18n in panels.php.
If I use for example, this `__('Dashboard','my-text-domain')` on other parts of my plugin, it works and return the translated string.
If I use the same function (`__('Dashboard','my-text-domain')`) in panels.php, then it return only the default language.

Why this is happening? I'm loading my text domains with the `plugins_loaded` hook.

**Comment by ghost** [comment]
I haven't tried to use i18 with GetHerbert yet but I would take a look at the panel class to see how it's being instantiated using a hook:
[https://github.com/getherbert/framework/blob/dev/Herbert/Framework/Panel.php](https://github.com/getherbert/framework/blob/dev/Herbert/Framework/Panel.php)

![wordpress-core-load-lifecycle](https://cloud.githubusercontent.com/assets/13212058/23342471/a4fa6f5c-fc0f-11e6-9e39-871c61db6f5e.png)

**Comment by angelocala94** [comment]
Solved by calling `load_plugin_textdomain` in plugin.php
