### ISSUE TITLE
How can I load both css and js for something like thickbox?

### ISSUE THREAD

**Issue by JunaidQadirB** [getherbert/herbert#18]
Thanks a bunch for the awesome framework. I've just started playing with it and already liking it.

So, today I wanted to add an image via the WordPres media uploader and I had an existing working code and i took my time to `herbertize` it.

Normally in WP to add built in scripts and styles we do:

`wp_enqueue_script('thickbox')` and `wp_enqueue_style('thickbox')` respectively.

But How can i do the same in Herbert?
I could :
`$plugin->enqueue->admin([
    'as' => 'thickbox',
        ]);`

to load the script but don't know how to load it's styles.

regards,

**Comment by jasonagnew** [comment]
Thanks for pointing this out. I’ll need to add it in, for now you could use the `add_thickbox()` function in your `enqueue.php` file to pull in thickbox.

**Comment by JunaidQadirB** [comment]
Awesome! It worked. Thanks
