### ISSUE TITLE
Multiple Plugins Based on GetHerbert Doesn't Work

### ISSUE THREAD

**Issue by kkeiper1103** [getherbert/herbert#23]
I was trying to get two plugins based on get herbert to work. I develop some plugins and am looking for something a little more standardized, so I started using this. I got through developing a beta of one plugin and went to start another one.

I had to deactivate the first getherbert based plugin before the second one would activate. I'm assuming it's because each getherbert based plugin tries to `define("HERBERT_CONFIG", true);`

**Comment by jasonagnew** [comment]
Yip there’s a namespace issue. Something I didn’t think about when I first built Herbert. It was spotted pretty quick so decided to rewrite it to avoid the issue:

https://github.com/getherbert/herbert/tree/rewrite

https://github.com/getherbert/framework

I plan this month to get the docs updated and get back to keeping on top of issues.

**Comment by gurkanoluc** [comment]
@jasonagnew hi there, I have quick question. The code in the rewrite branch is ready for production use but just doesn't have docs? Or is it still in development?

**Comment by jasonagnew** [comment]
Sorry for the long delay @kkeiper1103 @gurkanoluc - the rewrite is now complete and now on the dev branch. The core is on v0.9.5, I plan to make a few small changes over the next week as we get close to launching v1.
