### ISSUE TITLE
Any plans for custom post types?

### ISSUE THREAD

**Issue by adamtootle** [getherbert/herbert#31]
Just came across this and started messing around with it. I like it so far. Just wanted to ask if there were any plans for creating custom post types via Herbert? Adding custom meta boxes would also be nice. I saw there was an issue for a complete rewrite but I wasn't sure where to look for proposed ideas.

Thanks and keep up the good work guys!

**Comment by tobeycodes** [comment]
https://github.com/jjgrainger/wp-custom-post-type-class

**Comment by jasonagnew** [comment]
We’re just in the middle of fixing up v0.9 and I’ll include some info about CTPs in the docs this weekend. 

@schrapel Thanks for posting that package, looks interesting.

Cheers for using Herbert :)

**Comment by jasonagnew** [comment]
The rewrite is now live and working with example plugin coming this weekend. We don't currently abstract how CPTs are done. View the docs here: http://getherbert.com/0.9/custom-post-types

**Comment by adamtootle** [comment]
thanks for the updates guys!
