### ISSUE TITLE
Packaging plugins

### ISSUE THREAD

**Issue by andrewho83** [getherbert/herbert#35]
Once you have your plugin built, what's the process in building it/packaging it for distribution?

**Comment by jasonagnew** [comment]
1) Commit your vendor folder to your repo
2) Add a plugin to WordPress SVN:

http://ttmm.io/tech/how-to-publish-a-wordpress-plugin-subversion/

Working with Git & SVN:

https://gist.github.com/kasparsd/3749872

3) Make sure plugin works right with http://wpackagist.org/
