### ISSUE TITLE
Multiple Herbert plugins issue when using namespaced classes (e.g. Helper) in flat files

### ISSUE THREAD

**Issue by garethfoote** [getherbert/herbert#37]
Hi there,

I'm using two plugins both based on your latest release of Herbert (0.9.6). Firstly they do work together harmoniously in some use cases however a problem arises when I attempt to use the Helper (or any other namespaced class) in a flat file (e.g. customPostType.php). 

I've been investigating this and it seems that the first instance of Herbert encountered (for example in MyPluginA) will autoload any/all other Herbert plugins in the Worpdress plugins directory. However when it attempts to load another plugin (e.g. MyPluginB) I cannot use any namespaced classes in flat files in that plugin. Herbert\Framework\Application (in MyPluginA) is calling `loadPlugin()` before it has encountered the plugin.php file (for MyPluginB) and therefore hasn't included the composer generated autoloader, which sets up the autoloading for that plugin (as mentioned in the Namingspacing Your Plugin section of your docs http://getherbert.com/0.9). Therefore when attempting to 'use' a namespaced class (in MyPluginB), for example in `customPostTypes.php` the class doesn't exist. e.g:

```
use MyPluginB\Helper;
var_dump(class_exists('Helper')); // false
```

This is my interpretation of the issue, which might not be completely accurate. Hoping it might point you in the right direction. Since the issue appears to be related to the order of loading the best way to replicate the issue is to use a Helper in two flat files, e.g. customPostTypes.php. 

I'm not sure what the best method is to workaround this. Any suggestions welcome. 

g.

**Comment by jasonagnew** [comment]
Hey @garethfoote good spot and thanks looking into it. We've just pushed a fix - if you run `composer update` you should get the latest version now `0.9.9`.

**Comment by garethfoote** [comment]
Great. That's sorted it. Thanks for the prompt response.
