### ISSUE TITLE
Not able to make routes work

### ISSUE THREAD

**Issue by jorgepedret** [getherbert/herbert#44]
Hi, I'm trying to add a very simple route but I continue getting 404 no matter what. Here’s my code for routes.php

``` php
<?php namespace PromoSync;

/** @var \Herbert\Framework\Router $router */

$router->get([
  'as'   => 'simpleRoute',
  'uri'  => '/whyyoudontwork',
  'uses' => function () {
    echo "Hello World!"
  }
]);
```

I verified that the routes file is loaded in herbert.config.php

``` php
'routes' => [
    'PromoSync' => __DIR__ . '/app/routes.php'
],
```

Any advice? Am I forgetting anything? Thanks!

**Comment by jasonagnew** [comment]
One thing to check, routes requires permalinks to be enabled.

**Comment by jorgepedret** [comment]
Hey Jason, permalinks seem to be enabled.

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

**Comment by JunaidQadirB** [comment]
Did you re-save the permalinks from Settings->Permalinks?
Changing to default and save and then change back to last setting and save sometimes also works

**Comment by jorgepedret** [comment]
Hey JeyKeu, thanks for the suggestion. I tried to reset the permalinks 3 times, unfortunately it's still returning a 404.

Any other suggestions I could try? All I need is a semi-obscure endpoint that serves as a simple webhook for two different kind of events. Any help would be appreciated.

**Comment by jorgepedret** [comment]
I just noticed that all my permalinks are returning 404! Let me take a look at that and get back to you.

**Comment by jasonagnew** [comment]
Hi @jorgepedret 

Sorry for not responding sooner, its been a busy week. The [Debug This](https://wordpress.org/plugins/debug-this/) can be useful for finding issues with your install. Worth checking permissions of htaccess?

Also on side note, you'd normally use `return` instead of `echo` in your route.

``` php
$router->get([
  'as'   => 'simpleRoute',
  'uri'  => '/whyyoudontwork',
  'uses' => function () {
    return "Hello World!";
  }
]);
```

**Comment by jasonagnew** [comment]
And if you want to test routes outside of Herbert, you can include the following in your theme and it will add three routes `/route/one` `/route/two` `/route/three`

``` php
<?php

//Clear rewrite rules
add_action('wp_loaded', function ()
{
    flush_rewrite_rules();
});

//Add route tag
add_action('init', function ()
{
    add_rewrite_tag('%route_name%', '(.+)');
});

//Find templates
add_action('parse_request', function ($wp)
{
    if (array_key_exists('route_name', $wp->query_vars))
    {
        $name = $wp->query_vars['route_name'];

        switch ($name)
        {
            case 'one':
                echo 'route one';
                break;

            case 'two':
                echo 'route two';
                break;

            case 'three':
                echo 'route three';
                break;
        }

        die(0);
    }
});

//Add routes
add_action('init', function()
{
    add_rewrite_rule(
        'route/one',
        'index.php?route_name=one',
        'top'
    );

    add_rewrite_rule(
        'route/two',
        'index.php?route_name=two',
        'top'
    );

    add_rewrite_rule(
        'route/three',
        'index.php?route_name=three',
        'top'
    );

});
```

**Comment by jorgepedret** [comment]
Thanks a lot Jason! I just got it figured out by adding this to my vhost configuration

```
<Directory />
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
</Directory>
```

Just for future reference, I changed it from this:

```
<VirtualHost *:80>
  DocumentRoot "/Users/jorgepedret/src/clients/wpplugin/www"
  ServerName wpplugin
</VirtualHost>
```

To this:

```
<VirtualHost *:80>
  DocumentRoot "/Users/jorgepedret/src/clients/wpplugin/www"
  ServerName wpplugin
  <Directory />
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
  </Directory>
</VirtualHost>
```

Then restarted the MAMP server and it was all working like normal.

Thanks a lot for the suggestions. I've been burnt by this issue before and always forget to check the vhost file. Hope this helps other people in the future.
