### ISSUE TITLE
Enqueue Filter by Panel broke

### ISSUE THREAD

**Issue by ghost** [getherbert/herbert#45]
Enqueuing a script/css and filtering by panel throws an error, getPanels() not a function in Herbert/Framework/Enqueue.php line 185

Only tested on $enqueue->admin, doesn't work with '*' or with a named panel.

**Comment by jasonagnew** [comment]
Thanks for reporting, I'll fix this tomorrow.

**Comment by jasonagnew** [comment]
Sorry for the delay this is fixed now, run `composer update`

**Comment by Awais16** [comment]
can i enqueued once default jQuery is included by the theme?
