### ISSUE TITLE
Returning Response in shortcode "could not be converted to string"

### ISSUE THREAD

**Issue by tricki** [getherbert/herbert#53]
I created a shortcode tied to a controller method where I return a `Herbert\Framework\Response` object using the `view` function but I got an error saying it "could not be converted to string".
My solution to the problem was adding a `__toString()` method to the `Response` class which returns the body but this is just a temporary.

Is this a bug or am I doing something wrong? Should I open a pull request for the `__toString()` method.

**Comment by jasonagnew** [comment]
Sorry about that, run `composer update` and it should be working.

**Comment by 69dev69dev** [comment]
Hi @jasonagnew
i am newbie in wp plugin development...

i try for creating shortcode using Argument Names , eg:
`[showMe keyword=foo bar]`
but in view, i just get **foo**, not **foo bar**.
how i can showing foo bar as string not array ?

This my code : 

```
// shortcodes.php

$shortcode->add(
    'showMe',
    'myAppApi::showMeVal',
    [
        'keyword' => 'keyword'
    ]
);
```

and my api like this:

```
// api.php

$api->add('showMeVal', function($keyword) {
    return (new ShortcodeController)->showmeact($keyword);
});
```

Thanks so much for the great framework :)

**Comment by jeremyzahner** [comment]
@David-Kurniawan I guess @arippberger already answered your question in #122.
