### ISSUE TITLE
HerbertServiceProvider collation

### ISSUE THREAD

**Issue by terrylau2013** [getherbert/herbert#56]
$capsule->addConnection([
            'driver' => 'mysql',
            'host' => DB_HOST,
            'database' => DB_NAME,
            'username' => DB_USER,
            'password' => DB_PASSWORD,
            'charset' => DB_CHARSET,
            'collation' => 'utf8_unicode_ci',
            'prefix' => $wpdb->prefix
        ]);

Is the field 'collation' really need? If yes, I think shouldn't hard-code. If charset updated to utf8mb4 the collation utf8_unicode_ci is not vaild will throw SQLException.

**Comment by jasonagnew** [comment]
Thanks, this has been updated to pull the standard `DB_COLLATE` or falls back to the WordPress default `utf8_general_ci`
