### ISSUE TITLE
Shortcode fatal error

### ISSUE THREAD

**Issue by csrui** [getherbert/herbert#58]
I'm getting the following error trying to use shortcodes with herbert. Anyone else getting this?

Catchable fatal error: Object of class Herbert\Framework\Response could not be converted to string in /Volumes/Work/data/wp_tests/wp-includes/shortcodes.php on line 303

I've tried via API

```
$shortcode->add(
    'MyPluginShowPostName',
    'myPluginApi::showPostName'
);

...

$api->add('showPostName', function($postId)
{
    return (new PostController)->showPostName($postId);
});
```

And also via controller directly like so

```
$shortcode->add(
    'MyPluginShowPostName',
    __NAMESPACE__ . '\Controllers\PostController@showPostName'
);
```

**Comment by jasonagnew** [comment]
@csrui any chance you could run a `composer update` as I thought I'd fixed that issue yesterday.

**Comment by csrui** [comment]
Awesome!

It's working both ways, controller and API.

**Comment by csrui** [comment]
There's still something wrong with the shortcode...

The shortcode should appear between the two content

![my_custom_shirts___wordpress_testing_ground](https://cloud.githubusercontent.com/assets/205312/8939262/46a74794-355b-11e5-8eb6-eb9a808b1b10.png)
 sentences.

**Comment by jasonagnew** [comment]
Good spot, run `composer update` and that should be fixed. Make sure it pulls in `0.9.13` just incase it doesn't pick it up right away.

**Comment by csrui** [comment]
@jasonagnew Working fine now, closing the issue. Thanks
