### ISSUE TITLE
PluginAccessorTrait get_class() is not necessary

### ISSUE THREAD

**Issue by unstoppablecarl** [getherbert/herbert#6]
get_class() is not necessary here.

https://github.com/getherbert/herbert/blob/dev/framework/Traits/PluginAccessorTrait.php#L29

**Comment by jasonagnew** [comment]
Good spot, thanks.

**Comment by ConnorVG** [comment]
This is a hacky work around of having a custom `__isset`, know any better way of doing this @unstoppablecarl?

**Comment by unstoppablecarl** [comment]
I don't think there is another way to do it. but I do know that you do not need to have `get_class()` you can just use `$this`.

**Comment by ConnorVG** [comment]
The reason I used `get_class` is because then it checks the actual class not the object instance for the property. Though this is a non-issue for future progress (`PluginAccessorTrait` will be removed). Thanks for the input @unstoppablecarl.
