### ISSUE TITLE
Enqueue example with jQuery dependency

### ISSUE THREAD

**Issue by csrui** [getherbert/herbert#60]
Does enqueue support dependencies? is so, how can this be achieved?

Edit: Seems some tinkering would be necessary on Enqueue::buildInclude

Edit2: Easy solve, will do a fork

**Comment by PrafullaKumarSahu** [comment]
Here for your first question on dependency .

```
$enqueue->admin([
    'as'     => 'jquery',
    'src'    => 'jquery',
    'filter' => [ 'panel' => 'analytica-admin-settings' ]
]);

$enqueue->admin([
    'as'  => 'popup',
    'src' => Helper::assetUrl('/jquery/popup.js'), // => /resources/assets/js/popup.js
], 'footer');
```

and next two line , I am unable to understand.

**Comment by jeremyzahner** [comment]
@csrui Seems like this has been resolved for you. I'm closing the issue. Feel free to reopen it if you find the problem not to be fixed.
