### ISSUE TITLE
newbie docs?

### ISSUE THREAD

**Issue by lilmike** [getherbert/herbert#62]
Hi,
I was looking into using herbert, and it seems the docs could use a little updating -- not in being out of date, but being not as helpful to newcomers like myself. I've personally written a plugin for wordpress.org, but I haven't used herbert. I was looking at it, and even looking at the example plugin, I can barely get things to make sense in my head. Perhaps some docs with a start-to-finish of writing a mostly full plugin would be helpful, or something like that.
Thanks,
-Michael.

**Comment by jasonagnew** [comment]
Hi @lilmike Thanks for letting me know - I agree the docs aren't any good at the minute. I like the idea of building a plugin as a walkthrough. I'm away this weekend but I'll give it go when I'm back.

**Comment by csrui** [comment]
It would indeed be a great improvement on the documentation. 

@lilmike I'm loving Herbert so far.

**Comment by jeremyzahner** [comment]
I guess @lilmike might be referring to Herbert beeing based on mostly MVC principles. That makes it hard to get if you're not used to MVC in general.

@lilmike you should maybe give Silex a shot (http://silex.sensiolabs.org/). It's a good point of entry for learning MVC principles by learning by doing.

@onnimonni I think this issue should be closed.
