### ISSUE TITLE
How to use my model in a controller method?

### ISSUE THREAD

**Issue by ortegacmanuel** [getherbert/herbert#8]
Hi!

we have start workint with herbert but we have find this issue:

This is my code in activate.php

``` php
<?php

use Illuminate\Database\Capsule\Manager as Capsule;

$plugin->general->activate( function() use ($plugin) {

    Capsule::schema()->create('orders', function($table)
    {
        $table->increments('id');
        $table->string('title');
    });

});
```

This is my model in models/Orders.php

``` php
<?php

use Illuminate\Database\Eloquent\Model as Eloquent;

class Order extends Eloquent {
    protected $fillable = ['title'];
    public $timestamps = false;
}
```

This is my route rule

``` php
$plugin->route->get([
    'as'   => 'orderShow',
    'uri'  => '/order/:id'
], 'OrderController@show');
```

And this is my controller:

``` php
class OrderController extends BaseController {

    /**
    * Show the profile for the given user.
    */

    public function show($id)
    {

       $order = Order::find($id);

        return $this->view->render('order/show', ['titulo' => $order->title]);

    }
}
```

and this is $order = Order::find($id); is not working, why? Could you please help us

thanks for your help!

**Comment by jasonagnew** [comment]
After adding a Model or Controller you need rebuild the composer autoload by `composer dump-autoload`. I have a feeling it could be something simple like that. What error are you getting?

**Comment by ortegacmanuel** [comment]
Yes! You were right! We did not rebuild the composer autoload. Now it is working ok!
We have started developing with herbert this week and we are beginners in the wordpress plugin development world and by the first time we use composer.

We are reading a lot and would be really useful to have some plugin example built with herbert.

**Comment by ConnorVG** [comment]
The new setup will negate this annoying task of `composer du`'ing constantly, don't worry @kameleono :-)

**Comment by ortegacmanuel** [comment]
Nice!
