### ISSUE TITLE
Status or goals for v 1.0

### ISSUE THREAD

**Issue by sosensible** [getherbert/herbert#82]
I am very interested in this project but would like to know if it needs more community support or what the status of moving to a gold product will be.

**Comment by arippberger** [comment]
+1 - I think this project has a lot of potential - just need some direction on what I can do to help out

**Comment by jasonagnew** [comment]
Hi @sosensible & @arippberger 

Thanks for posting this. I’ve struggled a lot to find the time for Herbert. I would love to find a few people to help manage the project, along side that I’ll set up a Slack group where we could build a small community.

And I’m genuinely sorry that I haven’t been around to help with issues. It’s taken me some time to realise I’m the biggest problem with Herbert. I think the best route would be setting a contributor team of 2-3 people who have full access to everything. Keeping it small enough that we can have a solid vision for the project.

**Comment by arippberger** [comment]
Hi @jasonagnew -

Totally understandable. Let me know what I can do to help. I've only built one plugin with Herbert so far but will use it on any upcoming plugins to further my understanding of what's under the hood. Keep us updated on the Slack channel as well.

Thanks,

Alec

**Comment by smallfri** [comment]
I'm building my first plugin with Herbert and was also wondering about its future. I might be able to find time to contribute, just hit me up.

**Comment by onnimonni** [comment]
Hey @jasonagnew. I would also want to contribute to this project if this is still possible. I have made 2 big plugins using herbert. Many parts of herbert are really thoughtful and awesome but some parts need to have better documentation and more options for the devs. I believe this can become a major player in wp development with the help of the community.

**Comment by jasonagnew** [comment]
Hey everyone sorry for the delay. I've set up Slack group for people wanting to help. If you fill in this typeform you should get an invite within a day.

https://jagnew.typeform.com/to/bWrSO6

Be great to get a few of us talking about things, maybe on Monday?

**Comment by onnimonni** [comment]
I filled the typeform and monday sounds good!

**Comment by jeremyzahner** [comment]
@onnimonni @arippberger @jasonagnew I'm closing this issue for obvious reasons. I think we should discuss the roadmap on a proper milestone. I'll set that up soon. Feel free to reopen it if you don't agree.
