### ISSUE TITLE
Can you please tell me how can i get the custom post type posts (A Newbie Here)

### ISSUE THREAD

**Issue by syedolive** [getherbert/herbert#87]

**Comment by cranesandcaff** [comment]
http://getherbert.com/0.9/custom-post-types

Herbert doesn't change the way you manage CPT's, but it does offer suggestions in the docs for how to manage them. Does that answer your question?

**Comment by syedolive** [comment]
yes i can see how to create CPTs' . how can i display them to the front side by using herbert . actually i want to create a shortcode which can display the posts for my CPTs' only .

**Comment by jeremyzahner** [comment]
@syedolive I guess the best way to do such a thing with Herbert would be just to create a controller which does the query you'd want to have and then return the posts into the shortcodes view.
