### ISSUE TITLE
How do you call API within controller?

### ISSUE THREAD

**Issue by briankelleher** [getherbert/herbert#91]
I can't seem to figure it out, I've tried referencing what is called `$myPluginApi` (using my own var/namespace obviously), pulling in `Herbert\Framework\API`, pulling in `Namespace`, `Namespace\API`, and i just can't figure it out.  Anyone able to do this?  Is the API only available on non-twig templates? Isn't this sort of the opposite of its purpose?

**Comment by jasonagnew** [comment]
Hey @briankelleher 

Sorry for the delay. If you using an API in main template files of WordPress - you must first accessing them using `global`. Lets take this example:

`herbert.config.php`

``` php
    'apis' => [
        'myPluginApi' => __DIR__ . '/app/api.php'
    ],
```

`app/api.php`

``` php
<?php namespace MyPlugin;

/** @var \Herbert\Framework\API $api */

use Herbert\Framework\Models\Post;

$api->add('getPost', function($id)
{
    return Post::find($id);
});
```

Lets just use in our theme header.

``` php
<?php
   global $myPluginApi;
   $post = $myPluginApi->getPost(4);
   var_dump($post);
 ?>
```

**Comment by briankelleher** [comment]
Sorry I should have clarified - I was trying to access the APIs in my Controller file, similar to how you would pull in services to an AngularJS controller.  Just couldn't figure it out.  Maybe declaring as a global will work there, I haven't tried.

**Comment by jasonagnew** [comment]
Well you could use a global but APIs are intended to give other developers access to certain aspects of your plugin, so generally I see them as wrappers for methods that already exist. So lets say we had `getPosts` method on our api. It might have some validation logic to make sure the `$id` is passed correctly but after that it would just call a controller method.

``` php
<?php namespace MyPlugin;

/** @var \Herbert\Framework\API $api */

use MyPlugin\Controllers\PostController;

$api->add('getPost', function($id)
{
    return (new PostController)->getPost($id);
});
```

Therefore there would be no need to ever call your api within your plugin, instead you'd just call directly.

``` php
<?php

namespace MyPlugin\Controllers;

use MyPlugin\Controllers\PostController;

class AdminController
{
    ...
    public function index()
    {
        ...
        $post = (new PostController)->getPost($id);      
        return view('@MyPlugin/admin/index.twig');
    }
```

Hopefully that clears it up a little?

**Comment by briankelleher** [comment]
It does.  I've moved some of my utility API to helpers and the rest to controller logic.  Thanks for your input.
